//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multas
    {
        public int Id { get; set; }
        public int AdministradorId { get; set; }
        public int PrestamoId { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Motivo { get; set; }
        public bool Estado { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<int> CreacionId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> ModificacionId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Administradores Administradores { get; set; }
        public virtual Prestamos Prestamos { get; set; }
    }
}
