//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripciones
    {
        public int IdInscripcion { get; set; }
        public Nullable<int> IdTorneo { get; set; }
        public Nullable<int> IdEquipo { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public string Estado { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Torneos Torneos { get; set; }
    }
}
