//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEFEntities : DbContext
    {
        public BDEFEntities()
            : base("name=BDEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Canchas> Canchas { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<EstadisticasJugador> EstadisticasJugador { get; set; }
        public virtual DbSet<Inscripciones> Inscripciones { get; set; }
        public virtual DbSet<Jugadores> Jugadores { get; set; }
        public virtual DbSet<Partidos> Partidos { get; set; }
        public virtual DbSet<Resultados> Resultados { get; set; }
        public virtual DbSet<ResumenEstadisticasEquipo> ResumenEstadisticasEquipo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Torneos> Torneos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
