//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partidos()
        {
            this.EstadisticasJugador = new HashSet<EstadisticasJugador>();
            this.Resultados = new HashSet<Resultados>();
        }
    
        public int IdPartido { get; set; }
        public Nullable<int> IdTorneo { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<int> IdCancha { get; set; }
        public Nullable<int> IdEquipoLocal { get; set; }
        public Nullable<int> IdEquipoVisitante { get; set; }
        public string Estado { get; set; }
        public string Ronda { get; set; }
        public Nullable<int> OrdenJuego { get; set; }
        public Nullable<int> IdGanador { get; set; }
    
        public virtual Canchas Canchas { get; set; }
        public virtual Equipos Equipos { get; set; }
        public virtual Equipos Equipos1 { get; set; }
        public virtual Equipos Equipos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadisticasJugador> EstadisticasJugador { get; set; }
        public virtual Torneos Torneos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultados> Resultados { get; set; }
    }
}
