//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultados
    {
        public int IdResultado { get; set; }
        public Nullable<int> IdPartido { get; set; }
        public Nullable<int> GolesEquipoLocal { get; set; }
        public Nullable<int> GolesEquipoVisitante { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual Partidos Partidos { get; set; }
    }
}
