//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumenEstadisticasEquipo
    {
        public int IdTorneo { get; set; }
        public int IdEquipo { get; set; }
        public Nullable<int> PartidosJugados { get; set; }
        public Nullable<int> PartidosGanados { get; set; }
        public Nullable<int> PartidosPerdidos { get; set; }
        public Nullable<int> GolesFavor { get; set; }
        public Nullable<int> GolesContra { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Torneos Torneos { get; set; }
    }
}
