//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Torneos()
        {
            this.Inscripciones = new HashSet<Inscripciones>();
            this.Partidos = new HashSet<Partidos>();
            this.ResumenEstadisticasEquipo = new HashSet<ResumenEstadisticasEquipo>();
        }
    
        public int IdTorneo { get; set; }
        public string NombreTorneo { get; set; }
        public string Categoria { get; set; }
        public string Genero { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> CostoInscripcion { get; set; }
        public Nullable<decimal> PremioTotal { get; set; }
        public Nullable<int> NumeroPremiados { get; set; }
        public Nullable<int> IdOrganizador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripciones> Inscripciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partidos> Partidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResumenEstadisticasEquipo> ResumenEstadisticasEquipo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
