USE [master]
GO
/****** Object:  Database [db_AFP]    Script Date: 23/06/2025 14:07:06 ******/
CREATE DATABASE [db_AFP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_AFP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\db_AFP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_AFP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\db_AFP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [db_AFP] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_AFP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db_AFP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db_AFP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db_AFP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db_AFP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db_AFP] SET ARITHABORT OFF 
GO
ALTER DATABASE [db_AFP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db_AFP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db_AFP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db_AFP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db_AFP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db_AFP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db_AFP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db_AFP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db_AFP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db_AFP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [db_AFP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db_AFP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db_AFP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db_AFP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db_AFP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db_AFP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [db_AFP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db_AFP] SET RECOVERY FULL 
GO
ALTER DATABASE [db_AFP] SET  MULTI_USER 
GO
ALTER DATABASE [db_AFP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db_AFP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db_AFP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db_AFP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db_AFP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [db_AFP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'db_AFP', N'ON'
GO
ALTER DATABASE [db_AFP] SET QUERY_STORE = ON
GO
ALTER DATABASE [db_AFP] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [db_AFP]
GO
/****** Object:  Table [dbo].[AFP]    Script Date: 23/06/2025 14:07:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AFP](
	[AFPId] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Eliminado] [bit] NOT NULL,
 CONSTRAINT [PK_AFP] PRIMARY KEY CLUSTERED 
(
	[AFPId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Empleado]    Script Date: 23/06/2025 14:07:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleado](
	[EmpleadoId] [int] IDENTITY(1,1) NOT NULL,
	[DNI] [varchar](8) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Apellidos] [varchar](100) NOT NULL,
	[FechaNacimiento] [date] NOT NULL,
	[Eliminado] [bit] NOT NULL,
 CONSTRAINT [PK_Empleado] PRIMARY KEY CLUSTERED 
(
	[EmpleadoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Retiro]    Script Date: 23/06/2025 14:07:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Retiro](
	[RetiroId] [int] IDENTITY(1,1) NOT NULL,
	[EmpleadoId] [int] NOT NULL,
	[AFPId] [int] NOT NULL,
	[Monto] [decimal](16, 2) NOT NULL,
	[CuentaInterbancaria] [varchar](30) NOT NULL,
	[Eliminado] [bit] NOT NULL,
 CONSTRAINT [PK_Retiro] PRIMARY KEY CLUSTERED 
(
	[RetiroId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Retiro]  WITH CHECK ADD  CONSTRAINT [FK_Retiro_AFP] FOREIGN KEY([AFPId])
REFERENCES [dbo].[AFP] ([AFPId])
GO
ALTER TABLE [dbo].[Retiro] CHECK CONSTRAINT [FK_Retiro_AFP]
GO
ALTER TABLE [dbo].[Retiro]  WITH CHECK ADD  CONSTRAINT [FK_Retiro_Empleado] FOREIGN KEY([EmpleadoId])
REFERENCES [dbo].[Empleado] ([EmpleadoId])
GO
ALTER TABLE [dbo].[Retiro] CHECK CONSTRAINT [FK_Retiro_Empleado]
GO
USE [master]
GO
ALTER DATABASE [db_AFP] SET  READ_WRITE 
GO
